# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('sid', models.CharField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
                ('recipe', models.CharField(max_length=100)),
                ('picture', models.ImageField(blank=True, upload_to='sandwich_images')),
                ('rating', models.IntegerField(default=5)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sandwich',
            name='maker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SandwichClub_app.UserProfile'),
        ),
    ]
