# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichClub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('recipe', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='sandwich_images')),
                ('description', models.CharField(max_length=2000)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
