# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichClub_app', '0002_sandwich'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sandwich',
            name='id',
        ),
        migrations.AddField(
            model_name='sandwich',
            name='sid',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
