# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichClub_app', '0002_auto_20170321_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='sandwich_images'),
        ),
    ]
