# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichClub_app', '0003_auto_20170316_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='picture',
            field=models.ImageField(blank=True, upload_to='sandwich_images'),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='sandwich',
            name='sid',
            field=models.CharField(default=uuid.uuid4, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
