# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichClub_app', '0004_auto_20170316_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sandwich',
            name='sid',
            field=models.CharField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
