# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 22:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SandwichClub_app', '0005_auto_20170316_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 18, 22, 46, 26, 632000), verbose_name='date created'),
        ),
    ]
